development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://hamfricgfneych:ace23d58081ee5a568c87515ed1e3f9fb212a06ec9acd11634f88920759c3f93@ec2-107-20-193-206.compute-1.amazonaws.com:5432/d263r091j7dk8p
  channel_prefix: nameofapp_production
